name: Check S3 Buckets
on:
  push:
    branches: [ master ]
jobs:
  check-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION
      - name: List S3 Buckets
        run: aws s3 ls > s3-buckets.txt
      - name: Archive S3 list
        uses: actions/upload-artifact@v4
        with:
          name: s3-buckets
          path: s3-buckets.txt
